<a href="https://colab.research.google.com/github/SahithReddy211/DS_LAB-PROGRAMS/blob/main/DS_LAB10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Regression Models for Predictive Analytics
# Application: House Price Prediction and House Purchase Classification

import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression

# LINEAR REGRESSION
print("----- Linear Regression -----")
# Independent Variable (House Size in square feet)
X_linear = np.array([[1000], [1200], [1500], [1800], [2000]])
# Dependent Variable (House Price in lakhs)
y_linear = np.array([50, 55, 65, 80, 90])
# Create Linear Regression model
linear_model = LinearRegression()
# Train model
linear_model.fit(X_linear, y_linear)
# Predict price for new house
new_house_size = np.array([[1700]])
predicted_price = linear_model.predict(new_house_size)
print("Training House Sizes:")
print(X_linear.flatten())
print("\nTraining House Prices:")
print(y_linear)
print("\nPredicted Price for 1700 sq.ft house:")
print(predicted_price[0])
# ---------------------------------------------------
# LOGISTIC REGRESSION
# ---------------------------------------------------
print("\n\n----- Logistic Regression -----")
# Independent Variable (House Price in lakhs)
X_logistic = np.array([[40], [50], [60], [70], [80], [90]])

# Dependent Variable
# 0 = Not Purchased
# 1 = Purchased
y_logistic = np.array([0, 0, 0, 1, 1, 1])
# Create Logistic Regression model
logistic_model = LogisticRegression()
# Train model
logistic_model.fit(X_logistic, y_logistic)
# Predict whether customer will purchase
test_price = np.array([[75]])
purchase_prediction = logistic_model.predict(test_price)
# Probability prediction
purchase_probability = logistic_model.predict_proba(test_price)
print("Training House Prices:")
print(X_logistic.flatten())
print("\nPurchase Labels:")
print(y_logistic)
print("\nTest House Price:", test_price[0][0])
print("\nPurchase Prediction:")
print(purchase_prediction[0])
print("\nPrediction Probabilities:")
print(purchase_probability)


----- Linear Regression -----
Training House Sizes:
[1000 1200 1500 1800 2000]

Training House Prices:
[50 55 65 80 90]

Predicted Price for 1700 sq.ft house:
76.08823529411764


----- Logistic Regression -----
Training House Prices:
[40 50 60 70 80 90]

Purchase Labels:
[0 0 0 1 1 1]

Test House Price: 75

Purchase Prediction:
1

Prediction Probabilities:
[[0.00349394 0.99650606]]


Decision Trees

In [2]:
# Classification using Decision Tree
# Performance Evaluation Metrics
# Application: Student Pass/Fail Prediction
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ---------------------------------------------------
# INPUT DATA
# ---------------------------------------------------
# Features:
# [Study Hours, Attendance Percentage]
X = np.array([
    [2, 50],
    [3, 60],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
])
# Labels:
# 0 = Fail
# 1 = Pass
y = np.array([0, 0, 0, 1, 1, 1, 1, 1])
# ---------------------------------------------------
# TRAIN DECISION TREE MODEL
# ---------------------------------------------------
model = DecisionTreeClassifier(random_state=42)

model.fit(X, y)
# ---------------------------------------------------
# TEST DATA
# ---------------------------------------------------
X_test = np.array([
    [3, 55],
    [5, 72],
    [8, 88],
    [4, 60]
])
# Actual outputs
y_test = np.array([0, 1, 1, 0])
# Predict outputs
y_pred = model.predict(X_test)
# ---------------------------------------------------
# PERFORMANCE EVALUATION
# ---------------------------------------------------
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
# ---------------------------------------------------
# DISPLAY RESULTS
# ---------------------------------------------------

print("Actual Labels:")
print(y_test)
print("\nPredicted Labels:")
print(y_pred)
print("\nConfusion Matrix:")
print(cm)
print("\nAccuracy:")
print(accuracy)
print("\nError Rate:")
print(error_rate)
print("\nPrecision:")
print(precision)
print("\nRecall:")
print(recall)
print("\nF1-Score:")
print(f1)


Actual Labels:
[0 1 1 0]

Predicted Labels:
[0 1 1 0]

Confusion Matrix:
[[2 0]
 [0 2]]

Accuracy:
1.0

Error Rate:
0.0

Precision:
1.0

Recall:
1.0

F1-Score:
1.0
